---
# This playbook uses the consulting_assistants module to execute a prompt flow.
- hosts: localhost
  gather_facts: false
  environment:
    ANSIBLE_LIBRARY: ~/.ansible/plugins/modules
  tasks:
    - name: Execute prompt flow
      consulting_assistants:
        prompt: "What is 1+1? Just give me the answer"
        model_id_or_name: "Llama2 70B Chat"
        # assistant_id: "optional-assistant-id"
        # collection_id: "optional-collection-id"
        # system_prompt: "optional-system-prompt"
        # parameters: {"key1": "value1", "key2": "value2"}
        # substitution_parameters: {"key1": "value1", "key2": "value2"}
        # refresh_data: false
      register: consulting_assistants_result

    - name: Print consulting assistants result
      debug:
        var: consulting_assistants_result.response
